class StackUnderflowException(Exception):
    pass


class StackOverflowException(Exception):
    pass
